# Generated by Django 5.1.1 on 2024-10-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatingTableOne',
            fields=[
                ('name', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('Synergic_Calculator', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('ID_Card_Generator', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Inventory_Management', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Food_Chatbot', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Incident_Reporter', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Online_Banking_System', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Online_Voting_System', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Bus_Times', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Secret_Code', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Health_Dot', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Online_Attendance_using_Face_Recognition', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Heart_Disease_Prediction', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Exquisite_Checks', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Facemask_Detection_System', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('OTP_Verification', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Language_Translator', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Matrix_Calculator', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Project_Info', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Housing_Society_Management_System', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Hangman', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Virtual_Counselor', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Interview_IQ:Aptitude&Interview_Training_Game', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Steganography', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Controlling_Home_Appliances_using_Voice_Assistance', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Virtual_AI_Assistant', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('IV_Bag_Monitoring_&_Alert_System', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Virtual_Mouse', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Barrier_Buster', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Object_Detection', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Fraud_Detection', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Gesture_Control', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Plagiarism_Checker', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('E-Cart_Universe_&_AI_Virtual_Marker', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Word_Game', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
                ('Song_Recommendation_using_Face_Reaction', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', max_length=2)),
            ],
        ),
    ]
