# Generated by Django 5.1.1 on 2024-10-05 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RatingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingtableone',
            old_name='IV_Bag_Monitoring_&_Alert_System',
            new_name='IV_Bag_Monitoring_and_Alert_System',
        ),
    ]
