# Generated by Django 5.1.1 on 2024-10-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RatingApp', '0002_rename_iv_bag_monitoring___alert_system_ratingtableone_iv_bag_monitoring_and_alert_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratingtableone',
            old_name='E-Cart_Universe_&_AI_Virtual_Marker',
            new_name='E-Cart_Universe_and_AI_Virtual_Marker',
        ),
    ]
