# Generated by Django 5.1.1 on 2024-10-05 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RatingApp', '0003_rename_e_cart_universe___ai_virtual_marker_ratingtableone_e_cart_universe_and_ai_virtual_marker'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ETHICAL_EAGLES', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='ATTENDANCE TRACKER', max_length=2)),
                ('SUNFLOWER_SYNERGY', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='GRADENOTIFIER', max_length=2)),
                ('GRADENOTIFIER', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='AUTONOMOUS VEHICLE', max_length=2)),
                ('SONIC_SIRENS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='MUSIC PLAYER', max_length=2)),
                ('MUSIC_PLAYER', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='DRIVER DROWSINESS DETECTION', max_length=2)),
                ('TECH_SPARK', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='BANKING MANAGEMENT SYSTEM', max_length=2)),
                ('404_ERROR', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='IQ TEST BETWEEN DIFFERENT AGED PEOPLE', max_length=2)),
                ('APEXDEV', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='PLACEMENT MANAGEMENT SYSTEM', max_length=2)),
                ('TECH_TWINS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='TETRIS GAME', max_length=2)),
                ('SPARKLING_STARS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='TRAVEL CHATBOT', max_length=2)),
                ('CLEVER_CODERS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='TRAVEL AND TOURISM MANAGEMENT SYSTEM', max_length=2)),
                ('TRAVEL_AND_TOURISM_MANAGEMENT_SYSTEM', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='WIKIPEDIA SEARCH APPLICATION', max_length=2)),
                ('GPS_CODERS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='ONLINE EXAMINATION MANAGEMENT SYSTEM', max_length=2)),
                ('CODE_SMITHS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='FILE ORGANISER', max_length=2)),
                ('TECHNOZ', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='BLOGGING PLATFORM', max_length=2)),
                ('TECH_TITANS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='INTERACTIVE PORTFOLIO HUB', max_length=2)),
                ('ERROR_LIST', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='WEB SCRAPPING', max_length=2)),
                ('CODE_TECHNICIANS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='FITNESS PLAN GENERATOR', max_length=2)),
                ('FUTURE_DEVELOPERS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='BRAIN TEASERS', max_length=2)),
                ('INFINITY_ERRORS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='OTP GENERATOR', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='ThirdYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SLC-1', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='ECOMMERCE FOOD WEBSITE (USER MODULE)', max_length=2)),
                ('SLC-2', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='ECOMMERCE FOOD WEBSITE (ADMIN MODULE)', max_length=2)),
                ('404_NOT_FOUND', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='SPEECH EMOTION RECOGNITION', max_length=2)),
                ('LOGIC_KILLER', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='COMPREHENSIVE PLATFORM FOR QUESTION PAPERS', max_length=2)),
                ('IT_IMMORTALS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='SKILLMATCH PRO', max_length=2)),
                ('TECH_NINJAS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='WOMEN SAFETY APPLICATION', max_length=2)),
                ('DEBUT_CODERS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='BRIDGING GAPS', max_length=2)),
                ('QUARTO', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='WEB APPLICATION FOR DIRECT MARKET ACCESS TO FARMERS', max_length=2)),
                ('STELLAR_SQUAD', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='WASTE FOOD MANAGEMENT', max_length=2)),
                ('INNOVATORS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='OUTPASS MANAGEMENT SYSTEM', max_length=2)),
                ('VERSE_VILLAINS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='BOOKWORM UNITE', max_length=2)),
                ('TECH_TITANS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='CAR RENTAL SYSTEM', max_length=2)),
                ('NEW_YORK_SIRENS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='ONLINE AUCTION SYSTEM', max_length=2)),
                ('NULL_CODERS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='KEYLOGGER', max_length=2)),
                ("FLAMING_TRIO'S", models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='SIMULATION OF RAILWAY PLATFORM TICKET DISPENSING SYSTEM', max_length=2)),
                ('ELITE_CREW', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='RESUME BUILDER', max_length=2)),
                ('ROBO_RACERS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='BLUETOOTH CONTROLLED AURDINO CAR', max_length=2)),
                ('SMART_TECH', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='AUTOMATED PLANT DISEASE DETECTION SYSTEM USING DEEP LEARNING', max_length=2)),
                ('FIN-MENTORS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='SMART GARDEN IRRIGATION SYSTEM', max_length=2)),
                ('KODERS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='QUIZ GAME', max_length=2)),
                ('TECH_WIZARDS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='SALESMAN TRACKING SYSTEM', max_length=2)),
                ('CODE_CRUSHERS', models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='KNOWLEDGE APTITUDE PREP HUB', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='RatingTableOne',
        ),
        migrations.AddField(
            model_name='thirdyear',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='RatingApp.user'),
        ),
        migrations.AddField(
            model_name='secondyear',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='RatingApp.user'),
        ),
    ]
