# Generated by Django 5.1.1 on 2024-10-05 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RatingApp', '0004_secondyear_thirdyear_user_delete_ratingtableone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondyear',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_year_users', to='RatingApp.user'),
        ),
        migrations.AlterField(
            model_name='thirdyear',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_year_users', to='RatingApp.user'),
        ),
    ]
