# Generated by Django 5.1.1 on 2024-10-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RatingApp', '0005_alter_secondyear_user_alter_thirdyear_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='secondyear',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
