# Generated by Django 5.1.1 on 2024-10-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RatingApp', '0006_alter_secondyear_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='secondyear',
            old_name='GRADENOTIFIER',
            new_name='AUTONEXUS',
        ),
        migrations.RenameField(
            model_name='secondyear',
            old_name='MUSIC_PLAYER',
            new_name='DEADLINE_DOMINATORS',
        ),
        migrations.RenameField(
            model_name='secondyear',
            old_name='TRAVEL_AND_TOURISM_MANAGEMENT_SYSTEM',
            new_name='TECHNONGEMS',
        ),
        migrations.AddField(
            model_name='secondyear',
            name='CODE_CRACKERS',
            field=models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='WEB BASED WEATHER FORCASTING', max_length=2),
        ),
        migrations.AddField(
            model_name='secondyear',
            name='NOVA_SPIRE',
            field=models.CharField(choices=[('0', 'None'), ('1', '⭐'), ('2', '⭐⭐'), ('3', '⭐⭐⭐'), ('4', '⭐⭐⭐⭐'), ('5', '⭐⭐⭐⭐⭐')], default='0', help_text='CONVERTING E-BBOKS TO AUDIOBOOKS', max_length=2),
        ),
    ]
